-- CreateTable
CREATE TABLE `Income` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL,
    `Amount` INTEGER NOT NULL,
    `Date` DATETIME(3) NOT NULL,
    `description` TEXT NOT NULL,
    `source` ENUM('SALARY', 'FREELANCING', 'INVESTIMENTS', 'STOCKS', 'BANK_TRANSFERS', 'OTHER') NOT NULL DEFAULT 'SALARY',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
